---
title: "Introduction into Latent Class Analysis"
author: "Simon Kucharsky"
date: "Project has been made under Programming: the Next Step course at University of Amsterdam"
output: html_document
---

for code and further information, visit [Github](https://github.com/Kucharssim/LCAapp) page.

<script type="text/javascript">

  $(document).ready(function() {

    $('h1, h2, h3, h4, h5').each(function() {

      $(this).attr('id', $(this).html());
    });
  });
</script>


<a href="## What is LCA?">What it LCA?</a><br>
<a href="## How is LCA done?">How is LCA done?</a><br>
<a href="## How to work with the App?">How to work with the App?</a><br>

## What is LCA?

Latent Class Analysis is a statistical technique, a special case of mixture modelling. The focus of this approach is to find underlying (latent) categorical structure in the data which explains dependencies among the observed categorical variables. This method can be thus used if we want to find a distinct *classes* (groups) of individual cases which have similar answer patterns across all observed variables.

To ilustrate the idea, let's imagine a simple problem. Suppose you asked random people whether they will watch a 2017 Europa League final (Ajax Amsterdam vs Manchester United) and whether they put chocolate sprinkles on their toast. You observed the following frequencies (summarised in a contingency table):

```{r, echo=FALSE}
set.seed(100)
htmldata <- data.frame(final = c(sample(c("Yes", "No"), 400, TRUE, c(0.35, 0.65)),
                                 sample(c("Yes", "No"), 100, TRUE, c(0.15, 0.85))
                                 ),
                       sprinkles = c(sample(c("Yes", "No"), 400, TRUE, c(0.5, 0.5)),
                                 sample(c("Yes", "No"), 100, TRUE, c(0.1, 0.9))
                                 )
)
htmldata <- table(htmldata)
ch.test <- chisq.test(htmldata)
#print(xtable::xtable(table(htmldata)), type="html")
knitr::kable(htmldata)
```

If you applied a test for dependency between the two variables, you would find that the two variables relate to each other (for example, $\chi^2$ test of independence yields $\chi^2$ (1) = `r round(ch.test$statistic,2)`, p = `r round(ch.test$p.value, 3)`). Now, here's the question: Should we conclude a genuine relationship between the two variables? Probably every reasonable person would doubt that eating sprinkles makes you watch football, or that there is any other direct relationship between those two variables. In this case, it is likely that the relationship between the variables is spurious, caused by other factor(s) we didn't observe. For example, one explanation could be that this relationship might be explained by whether a person is dutch or not (dutch people are more likely on average watch a final game featuring dutch club, and they are also more likely to put sprinkles on their toast).

And this is where LCA comes in handy, becase using this technique, we *assume* that the relationship between the variables *is spurious* and caused by mixture of different populations with different answer patterns. By conditioning on the group membership, the variables should become unrelated. (*Disclaimer: The fact that that we assume the variables unrelated under conditioning on the class membership does not mean we cannot conduct LCA on data where we do not observe relationship between the variables in the first place. That could be caused by a special case of mixture similar to a suppressor effect in regression context*)

## How is LCA done?

